export enum TipoInsumoEnum {
  FERTILIZANTE = "FERTILIZANTE",
  PESTICIDA = "PESTICIDA",
  HERBICIDA = "HERBICIDA",
  SEMILLA = "SEMILLA",
  HERRAMIENTA = "HERRAMIENTA",
  MAQUINARIA = "MAQUINARIA",
  OTRO = "OTRO",
}
